Repository bucket-back/bucket-back-backend, pull requests merged in 2023-11, with the labels that each got.

#26 [NO-JIRA] review 엔티티에서 item id를 가지도록 변경
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewAppender.java
  src/main/java/com/programmers/bucketback/domains/review/domain/Review.java
Labels: refactor, SPRINT3

#25 [OMCT-93] Vote 삭제 기능 구현
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteRemover.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3

#31 [NO-JIRA] 회원 비회원 구분 로직 추가
  src/main/java/com/programmers/bucketback/domains/common/MemberUtils.java
  src/main/java/com/programmers/bucketback/global/config/security/SecurityUtils.java
Labels: SPRINT3

#29 [NO-JIRA] swagger authentication 설정 로직 추가
  src/main/java/com/programmers/bucketback/global/config/SwaggerConfiguration.java
Labels: enhancement, SPRINT3

#24 [OMCT-92] Vote 참여 기능 구현
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteParticipateRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteManager.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteReader.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteRemover.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoterAppender.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Voter.java
  src/main/java/com/programmers/bucketback/domains/vote/repository/VoterRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3

#27 [OMCT-44] Review 수정 기능 추가
  src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewModifier.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewReader.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewValidator.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3

#35 [NO-JIRA] MySQL 관련 의존성 추가
  build.gradle
Labels: SPRINT3

#34 [OMCT-37] 아이템 상세 조회 기능 구현
  src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetResponse.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/MemberItemChecker.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/GetItemServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewStatistics.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepository.java
Labels: enhancement, SPRINT3

#36 [OMCT-37] 멤버 아이템 삭제 기능 추가
  src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/MemberItemReader.java
  src/main/java/com/programmers/bucketback/domains/item/application/MemberItemRemover.java
  src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
Labels: enhancement, SPRINT3

#33 [OMCT-94] 투표 상세 조회 기능 구현
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/application/OptionItem.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteCounter.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteInfo.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoterReader.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/GetVoteServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/repository/VoterRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3

#32 [OMCT-72] bucket조회 및 커서 페이징 구현 및 버킷 관련 나머지 로직 수정
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketGetByCursorRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetResponse.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketContent.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketModifier.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketRemover.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketContent.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketItemContent.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketSummary.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/ItemImage.java
  src/main/java/com/programmers/bucketback/domains/bucket/domain/Bucket.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketItemRepository.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepository.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/common/vo/CursorPageParameters.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java
  src/main/java/com/programmers/bucketback/domains/member/repository/MemberRepository.java
  src/main/java/com/programmers/bucketback/global/config/QuerydslConfig.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: refactor, enhancement, SPRINT3

#38 [OMCT-99] 키워드로 아이템 이름 가져오기 기능 구현
  src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetNamesResponse.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemFinder.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/GetItemNamesServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemNameGetResult.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepository.java
Labels: enhancement, SPRINT3

#37 [OMCT - 86] Inventory 생성
  src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/request/InventoryCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/request/InventoryUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryAppender.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReader.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/vo/InventoryContent.java
  src/main/java/com/programmers/bucketback/domains/inventory/domain/Inventory.java
  src/main/java/com/programmers/bucketback/domains/inventory/domain/InventoryItem.java
  src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3

#41 [NO-JIRA] CICD.yml에 mail properties 설정 추가
  .github/workflows/CICD.yml
Labels: SPRINT3

#39 [OMCT-73] 이메일 중복 확인 + 인증번호 전송 기능 구현
  build.gradle
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckEmailRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberCheckEmailResponse.java
  src/main/java/com/programmers/bucketback/domains/member/application/EmailSender.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberChecker.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/repository/MemberRepository.java
  src/main/java/com/programmers/bucketback/global/config/MailConfiguration.java
  src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3

#40 [NO-JIRA] ItemInfo 클래스 생성 및 response 수정
  src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetResponse.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemMapper.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/GetItemServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/item/application/vo/ItemInfo.java
Labels: enhancement, SPRINT3

#43 [OMCT-123] bucket api 통일, 변수명 수정
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketModifier.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketContent.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketItemContent.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/ItemImage.java
  src/main/java/com/programmers/bucketback/domains/common/vo/CursorRequest.java
Labels: refactor, SPRINT3

#44 [NO-JIRA] member info 개념객체 추가
  src/main/java/com/programmers/bucketback/domains/member/application/vo/MemberInfo.java
Labels: enhancement, SPRINT3

#42 [OMCT - 87] Inventory 수정 및 삭제 기능 구현
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketRemover.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketItemRepository.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepository.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/request/InventoryCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/request/InventoryUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryAppender.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryModifier.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReader.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryRemover.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/vo/InventoryCreateContent.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/vo/InventoryUpdateContent.java
  src/main/java/com/programmers/bucketback/domains/inventory/domain/Inventory.java
  src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryItemRepository.java
  src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3

#45 [OMCT-88] Inventory 조회 및 요약정보 목록 조회
  src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketItem.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoriesGetResponse.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryGetResponse.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryInfoSummary.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryItemGetResponse.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReader.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  src/main/java/com/programmers/bucketback/domains/inventory/domain/InventoryItem.java
  src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepository.java
  src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepositoryForSummary.java
  src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepositoryForSummaryImpl.java
  src/main/java/com/programmers/bucketback/domains/item/application/vo/ItemInfo.java
Labels: enhancement, SPRINT3

#47 [OMCT-89] 피드 생성 로직 구현
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java
  src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  src/main/java/com/programmers/bucketback/domains/feed/api/request/FeedContent.java
  src/main/java/com/programmers/bucketback/domains/feed/api/request/FeedCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedAppender.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedModifier.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedRemover.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/FeedItem.java
  src/main/java/com/programmers/bucketback/global/config/SwaggerConfiguration.java
Labels: enhancement, SPRINT3

#48 [OMCT-42] 아이템 목록 조회 기능 구현
  src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemCursorReader.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/GetItemByCursorServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/item/application/vo/ItemCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/item/application/vo/ItemSummary.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepository.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java
Labels: enhancement, SPRINT3

#46 [OMCT-98] 리뷰 목록 조회 커서방식으로 구현
  src/main/java/com/programmers/bucketback/domains/member/application/vo/MemberInfo.java
  src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewCursorReader.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
  src/main/java/com/programmers/bucketback/domains/review/application/dto/GetReviewByCursorServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/review/application/vo/ReviewCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/review/application/vo/ReviewSummary.java
  src/main/java/com/programmers/bucketback/domains/review/domain/Review.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepository.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursorImpl.java
Labels: enhancement, SPRINT3

#49 [OMCT-124] 인벤토리 로직 전체 리팩토링
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/common/Hobby.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/request/InventoryCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryInfoSummary.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryModifier.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReader.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  src/main/java/com/programmers/bucketback/domains/inventory/domain/Inventory.java
  src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepositoryForSummaryImpl.java
Labels: refactor, SPRINT3

#50 [OMCT-90] 피드 수정 및 삭제 로직 구현
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  src/main/java/com/programmers/bucketback/domains/feed/api/request/FeedCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/feed/api/request/FeedUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedAppender.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedModifier.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedRemover.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedCreateContent.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedUpdateContent.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3

#51 [OMCT-39] 아이템 등록 기능 추가
  src/main/java/com/programmers/bucketback/domains/item/application/EnrollItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/EnrollItemValidator.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemAppender.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3

#52 [OMCT-95] Vote 조건 검색 + 커서 페이지네이션 구현
  src/main/java/com/programmers/bucketback/domains/common/vo/CursorPageParameters.java
  src/main/java/com/programmers/bucketback/domains/common/vo/CursorRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteAppender.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteInfo.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteReader.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteRemover.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteSortCondition.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteStatusCondition.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteSummary.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/GetVotesServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepository.java
  src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT4

#57 [OMCT-130] 피드 좋아요 및 좋아요 취소 기능 구현
  src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedAppender.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedRemover.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/FeedLike.java
  src/main/java/com/programmers/bucketback/domains/feed/repository/FeedLikeRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT4

#59 [OMCT-127] Feed 댓글 생성
  src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentAppender.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  src/main/java/com/programmers/bucketback/domains/comment/domain/Comment.java
  src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepository.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT4

#56 [OMCT-158] 리뷰 삭제 기능 추가
  src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewRemover.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
Labels: enhancement, SPRINT4

#55 [OMCT-137] 취미 조회 기능 추가
  src/main/java/com/programmers/bucketback/domains/hobby/HobbyController.java
  src/main/java/com/programmers/bucketback/domains/hobby/api/dto/response/HobbyGetResponse.java
  src/main/java/com/programmers/bucketback/domains/hobby/application/HobbyService.java
Labels: enhancement, SPRINT4

#58 [NO-JIRA] 아이템 도메인 잘못된 경로 수정
  src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
Labels: bug, SPRINT4

#60 [NO-JIRA] 리뷰 목록 조회할 경우 중복 조회 되는 버그 수정
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewCursorReader.java
  src/main/java/com/programmers/bucketback/domains/review/application/vo/ReviewCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/review/application/vo/ReviewSummary.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursorImpl.java
Labels: enhancement, SPRINT4

#53 [OMCT-133] 버킷 수정을 위한 MemberItem 조회
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetMemberItemResponse.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketMemberItemCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketMemberItemSummary.java
  src/main/java/com/programmers/bucketback/domains/bucket/domain/Bucket.java
  src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java
  src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketItem.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/FeedItem.java
  src/main/java/com/programmers/bucketback/domains/item/application/MemberItemChecker.java
  src/main/java/com/programmers/bucketback/domains/item/application/MemberItemReader.java
  src/main/java/com/programmers/bucketback/domains/item/domain/MemberItem.java
  src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
  src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursorImpl.java
Labels: enhancement, SPRINT4

#61 [OMCT-136] 피드 댓글 수정 기능 추가
  src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentModifyRequest.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentModifier.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentReader.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentValidator.java
  src/main/java/com/programmers/bucketback/domains/comment/domain/Comment.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT4

#62 [OMCT-140] Vote 취소 기능 구현
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteManager.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/repository/VoterRepository.java
Labels: enhancement, SPRINT4

#54 [OMCT-132]] Inventory 수정을 위한 내가 리뷰한 아이템 조회 기능 구현
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryGetReviewedItemResponse.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryInfoSummary.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventorReviewedItemCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReader.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReviewItemSummary.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepositoryForSummaryImpl.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemReader.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewReader.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepository.java
Labels: enhancement, SPRINT4

#63 [OMCT-128] 댓글 채택 기능 구현
  src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentModifier.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentReader.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  src/main/java/com/programmers/bucketback/domains/comment/domain/Comment.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT4

#64 [OMCT-129] 피드 댓글 목록 조회
  src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/response/CommentGetCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentReader.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepository.java
  src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/comment/repository/CommentSummary.java
Labels: enhancement, SPRINT4

#66 [OMCT-126] Feed 상세 조회 구현
  src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  src/main/java/com/programmers/bucketback/domains/feed/api/response/FeedGetResponse.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/feed/application/dto/response/GetFeedServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedInfo.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedItemInfo.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java
Labels: enhancement, SPRINT4

#65 [OMCT-135] 피드 댓글 삭제 기능 추가
  src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentRemover.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
Labels: enhancement, SPRINT4

#68 NO-ZIRA: 아이템 상세조회 및 리뷰 평점 버그 수정
  src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewStatistics.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepository.java
Labels: bug, SPRINT4

#72 [NO-JIRA] Member 버그 수정 및 유효성 검증 추가
  src/main/java/com/programmers/bucketback/domains/comment/domain/Comment.java
  src/main/java/com/programmers/bucketback/domains/comment/domain/vo/Content.java
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberLoginResponse.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberAppender.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberChecker.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberManager.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberModifier.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberRemover.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberUpdater.java
  src/main/java/com/programmers/bucketback/domains/member/application/SecurityManager.java
  src/main/java/com/programmers/bucketback/domains/member/application/dto/response/LoginMemberServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/member/domain/LoginInfo.java
  src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  src/main/java/com/programmers/bucketback/domains/member/domain/MemberStatus.java
  src/main/java/com/programmers/bucketback/domains/member/domain/Role.java
  src/main/java/com/programmers/bucketback/domains/member/domain/vo/Introduction.java
  src/main/java/com/programmers/bucketback/domains/member/domain/vo/LoginInfo.java
  src/main/java/com/programmers/bucketback/domains/member/domain/vo/MemberStatus.java
  src/main/java/com/programmers/bucketback/domains/member/domain/vo/Nickname.java
  src/main/java/com/programmers/bucketback/domains/member/domain/vo/Role.java
  src/main/java/com/programmers/bucketback/domains/member/repository/MemberRepository.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/vo/Content.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: bug, enhancement, SPRINT4

#71 [NO-JIRA] Member 리팩토링
  src/main/java/com/programmers/bucketback/domains/member/application/MemberAppender.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberModifier.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
Labels: refactor, SPRINT4

#70 [NO-JIRA] Vote 버그 수정
  src/main/java/com/programmers/bucketback/domains/common/Hobby.java
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteReader.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/VoteSortCondition.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/VoteStatusCondition.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/GetVotesServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
  src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: bug, SPRINT4

#69 [NO-JIRA] Vote 리팩토링
  src/main/java/com/programmers/bucketback/domains/common/Hobby.java
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/application/OptionItem.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteAppender.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteManager.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteReader.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteSortCondition.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteStatusCondition.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteSummary.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoterReader.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/CreateVoteServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/VoteSortCondition.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/VoteStatusCondition.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/GetVoteServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/GetVotesServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VoteCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VoteInfo.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VoteSummary.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Voter.java
  src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: refactor, SPRINT4

#73 [NO-JIRA] Feed 상세 조회 & Comment 생성, 채택 리팩토링
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentAppender.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentModifier.java
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedInfo.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  src/main/java/com/programmers/bucketback/domains/member/application/vo/MemberInfo.java
Labels: refactor, SPRINT4

#67 [OMCT-138] 마이페이지 조회
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketProfile.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepository.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReader.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/vo/InventoryProfile.java
  src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepository.java
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberGetMyPageResponse.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/application/vo/MemberProfile.java
  src/main/java/com/programmers/bucketback/domains/member/application/vo/MyPage.java
Labels: enhancement, SPRINT4

#75 [OMCT-134]-피드목록 조회 기능 추가
  src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  src/main/java/com/programmers/bucketback/domains/feed/api/response/FeedGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedCursorReader.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedSortCondition.java
  src/main/java/com/programmers/bucketback/domains/feed/application/dto/response/FeedGetByCursorServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedCursorItem.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedCursorSummaryLike.java
  src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepository.java
  src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
Labels: enhancement, SPRINT5

#74 [OMCT-166] 버킷 전체 리팩토링(협의사항 반영, but 커서는 협의 후 반영)
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetMemberItemResponse.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetResponse.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketModifier.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketRemover.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketContent.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketGetServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketItemContent.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketSummary.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/ItemIdRegistry.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/ItemImage.java
  src/main/java/com/programmers/bucketback/domains/bucket/domain/Bucket.java
  src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java
  src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedInfo.java
  src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: refactor, SPRINT5

#88 [OMCT-205] security cors 설정 및 인증인가 api 선별
  src/main/java/com/programmers/bucketback/global/config/security/SecurityConfiguration.java
Labels: bug, enhancement, SPRINT5

#86 [NO-JIRA] VO 추출로 인한 커서 목록 조회 안되는 버그 해결
  src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursorImpl.java
Labels: bug, SPRINT5

#84 [OMCT-208] 회원, 투표, 피드 상세 조회, 댓글 생성, 댓글 채택 API DTO 유효성 검증 추가
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckEmailRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckNicknameRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java
  src/main/java/com/programmers/bucketback/domains/member/domain/vo/LoginInfo.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteParticipateRequest.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT5

#79 [OMCT-207] 만료 JWT 토큰 예외 처리
  src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT5

#87 [OMCT-200] 아이템 버그 수정 및 유효성 검사 추가
  src/main/java/com/programmers/bucketback/domains/common/Hobby.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/request/ItemEnrollRequest.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemAddRequest.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemCursorReader.java
  src/main/java/com/programmers/bucketback/domains/item/application/MemberItemAppender.java
  src/main/java/com/programmers/bucketback/domains/item/application/MemberItemValidator.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: bug, enhancement, SPRINT5

#91 [OMCT-198] 리뷰 리팩토링
  src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewAppender.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewCursorReader.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewModifier.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
  src/main/java/com/programmers/bucketback/domains/review/application/dto/GetReviewByCursorServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewGetByCursorServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/review/application/vo/ReviewContent.java
  src/main/java/com/programmers/bucketback/domains/review/domain/Review.java
Labels: refactor, SPRINT5

#97 [NO-JIRA] PR 리뷰 완료된 브랜치를 main에 merge하기위한 PR요청
  src/main/java/com/programmers/bucketback/domains/common/Hobby.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/request/ItemEnrollRequest.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemAddRequest.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemCursorReader.java
  src/main/java/com/programmers/bucketback/domains/item/application/MemberItemAppender.java
  src/main/java/com/programmers/bucketback/domains/item/application/MemberItemValidator.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursor.java
  src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java
  src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: SPRINT5

#85 [OMCT-206] Swagger 설명 추가
  src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckEmailRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckNicknameRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteParticipateRequest.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT5

#82 [NO-JIRA] 서비스 DTO 네이밍 수정
  src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  src/main/java/com/programmers/bucketback/domains/feed/api/response/FeedGetResponse.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/feed/application/dto/response/FeedGetServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberLoginResponse.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberManager.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/application/dto/response/MemberLoginServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteAppender.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteReader.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/VoteCreateServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VoteGetServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VotesGetServiceResponse.java
Labels: refactor, SPRINT5

#77 [OMCT-167] 인벤토리 전체 리팩토링(커서페이징 제외)
  src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/request/InventoryCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/request/InventoryUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryCreateResponse.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryGetResponse.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryInfoSummary.java
  src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryItemGetResponse.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryAppender.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryModifier.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReader.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryRemover.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/dto/InventoryGetServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/vo/InventoryCreateContent.java
  src/main/java/com/programmers/bucketback/domains/inventory/application/vo/InventoryUpdateContent.java
  src/main/java/com/programmers/bucketback/domains/inventory/domain/Inventory.java
  src/main/java/com/programmers/bucketback/domains/inventory/domain/InventoryItem.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: refactor, SPRINT5

#80 [OMCT-166] 버킷 리팩토링 검증로직 추가
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketCreateResponse.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketModifier.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: refactor, SPRINT5

#98 [NO-JIRA] 이전 PR 중복 - Swagger 설정
  src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckEmailRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckNicknameRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteParticipateRequest.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: SPRINT5

#92 [OMCT-214] 리뷰 생성할 경우 review id 반환
  src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewCreateResponse.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewAppender.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
Labels: enhancement, SPRINT5

#94 [OMCT-210] 피드 댓글 리팩토링
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
Labels: refactor, SPRINT5

#96 [OMCT-211] feed 댓글 검증
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentModifyRequest.java
Labels: bug, enhancement, SPRINT5

#100 [NO-JIRA] 크롤러에서 예외를 발생할 경우 의도한 예외를 던질 수 있도록 예외 전환하는 기능 추가
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/CoupangCrawler.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/DanawaCrawler.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/NaverCrawler.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT5

#101 [NO-JIRA] 아이템, 리뷰, 댓글에 대해 swagger 설명 추가
  src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentModifyRequest.java
  src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/request/ItemEnrollRequest.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemAddRequest.java
  src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java
Labels: enhancement, SPRINT5

#102 [NO-JIRA] hobby api 반환 목록 수정
  src/main/java/com/programmers/bucketback/domains/hobby/HobbyController.java
  src/main/java/com/programmers/bucketback/domains/hobby/api/dto/response/HobbyGetResponse.java
  src/main/java/com/programmers/bucketback/domains/hobby/api/dto/response/HobbyItem.java
  src/main/java/com/programmers/bucketback/domains/hobby/application/HobbyService.java
Labels: enhancement, SPRINT5

#103 [OMCT-224] 로그인 하지 않을 경우 멤버 아이디를 요청할 때 null 반환
  src/main/java/com/programmers/bucketback/domains/common/MemberUtils.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedCursorReader.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemEnrollService.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/global/config/security/SecurityUtils.java
Labels: enhancement, SPRINT5

#104 [OMCT-225] 피드 목록 조회 리팩토링
  src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  src/main/java/com/programmers/bucketback/domains/feed/application/FeedSortCondition.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedCursorSummary.java
  src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedCursorSummaryLike.java
  src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
Labels: enhancement, SPRINT5

#99 [OMCT-192] 커서 유틸 클래스 적용
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetByCursorResponse.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketSummary.java
  src/main/java/com/programmers/bucketback/domains/common/CursorIdParser.java
  src/main/java/com/programmers/bucketback/domains/common/CursorSummary.java
  src/main/java/com/programmers/bucketback/domains/common/CursorUtils.java
Labels: refactor, SPRINT5

#89 [OMCT-191] AOP를 이용한 회원 레벨 시스템 구현
  src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  src/main/java/com/programmers/bucketback/domains/member/application/vo/MemberInfo.java
  src/main/java/com/programmers/bucketback/domains/member/domain/Level.java
  src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewCreateResponse.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
  src/main/java/com/programmers/bucketback/global/level/PayPoint.java
  src/main/java/com/programmers/bucketback/global/level/PointManagerAop.java
Labels: enhancement, SPRINT5

#105 [NO-JIRA] 닉네임 validation max size 변경, 비밀번호 swagger example 수정
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckNicknameRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java
Labels: bug, SPRINT5

#109 [OMCT-231] 멀티모듈을 위한 투표 리팩토링(with 커서 리팩토링)
  api/src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByCursorResponse.java
  api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetResponse.java
  api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  api/src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/VoteCreateServiceRequest.java
  api/src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VoteGetServiceResponse.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/domain/Voter.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/domain/vo/Content.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteAppender.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteReader.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteCreateImplRequest.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteCursorSummary.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteInfo.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteSortCondition.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteStatusCondition.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteSummary.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/request/VoteCreateServiceRequest.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/response/VoteCursorSummary.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/response/VoteGetServiceResponse.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/response/VoteSummary.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/response/VotesGetServiceResponse.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursor.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursorImpl.java
Labels: refactor, SPRINT5

#107 [OMCT-234] 멀티모듈을 위한 인벤토리 리팩토링(with 커서 리팩토링)
  api/src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  api/src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryGetReviewedItemResponse.java
  api/src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  domain/src/main/java/com/programmers/bucketback/domains/inventory/domain/Inventory.java
  domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReader.java
  domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventorReviewedItemCursorSummary.java
  domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryGetResponse.java
  domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryItemGetResponse.java
  domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryReviewItemSummary.java
Labels: refactor, SPRINT5

#108 [OMCT-233] 멀티모듈을 위한 아이템 리팩토링(with 커서 리팩토링)
  api/src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  api/src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemAddRequest.java
  api/src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetByCursorResponse.java
  api/src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetNamesResponse.java
  api/src/main/java/com/programmers/bucketback/domains/item/application/ItemEnrollService.java
  api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  api/src/main/java/com/programmers/bucketback/domains/item/application/MemberItemValidator.java
  api/src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemCreateServiceRequest.java
  api/src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemGetByCursorServiceResponse.java
  api/src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemGetNamesServiceResponse.java
  api/src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemNameGetResult.java
  api/src/main/java/com/programmers/bucketback/domains/item/application/dto/MemberItemAddServiceRequest.java
  domain/src/main/java/com/programmers/bucketback/domains/item/domain/Item.java
  domain/src/main/java/com/programmers/bucketback/domains/item/domain/MemberItem.java
  domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemAppender.java
  domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemCursorReader.java
  domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemFinder.java
  domain/src/main/java/com/programmers/bucketback/domains/item/model/ItemCreateServiceRequest.java
  domain/src/main/java/com/programmers/bucketback/domains/item/model/ItemCursorSummary.java
  domain/src/main/java/com/programmers/bucketback/domains/item/model/ItemGetByCursorServiceResponse.java
  domain/src/main/java/com/programmers/bucketback/domains/item/model/ItemNameGetResult.java
  infrastructure/build.gradle
  infrastructure/src/main/java/com/programmers/bucketback/crawling/CoupangCrawler.java
  infrastructure/src/main/java/com/programmers/bucketback/crawling/DanawaCrawler.java
  infrastructure/src/main/java/com/programmers/bucketback/crawling/ItemCrawlerResult.java
  infrastructure/src/main/java/com/programmers/bucketback/crawling/NaverCrawler.java
  infrastructure/src/main/java/com/programmers/bucketback/crawling/WebCrawler.java
Labels: SPRINT5

#110 [OMCT-240] 멀티모듈을 위한 리뷰 리팩토링(with 커서 리팩토링)
  api/src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetByCursorResponse.java
  api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
  api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewValidator.java
  api/src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewGetByCursorServiceResponse.java
  domain/src/main/java/com/programmers/bucketback/domains/review/domain/Review.java
  domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewCursorReader.java
  domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewStatistics.java
  domain/src/main/java/com/programmers/bucketback/domains/review/model/ReviewCursorSummary.java
Labels: refactor, SPRINT5

#112 [OMCT-244] 멀티모듈을 위한 회원 리팩토링
  api/src/main/java/com/programmers/bucketback/domains/member/application/MemberSecurityManager.java
  api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  api/src/main/java/com/programmers/bucketback/global/config/security/SecurityManager.java
  domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/LoginInfo.java
  domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/Nickname.java
  domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberAppender.java
  domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberChecker.java
  domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
  infrastructure/src/main/java/com/programmers/bucketback/mail/EmailSender.java
Labels: refactor, SPRINT5

#115 [OMCT-245] 멀티모듈을 위한 피드 목록 조회 리팩토링
  api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  api/src/main/java/com/programmers/bucketback/domains/feed/api/response/FeedGetByCursorResponse.java
  api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedCursorReader.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedCursorSummaryLike.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedGetByCursorResponse.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedGetByCursorServiceResponse.java
Labels: refactor, SPRINT5

#113 [NO-JIRA] api-module 에서 spring-jpa 의존성을 제거
  api/build.gradle
  api/src/main/java/com/programmers/bucketback/global/config/JpaAuditingConfiguration.java
  api/src/main/java/com/programmers/bucketback/global/config/security/ApplicationConfiguration.java
  api/src/main/java/com/programmers/bucketback/global/level/PointManagerAop.java
  domain/src/main/java/com/programmers/bucketback/common/cursor/CursorUtils.java
  domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberAppender.java
Labels: refactor, SPRINT5

#116 [OMCT-248] 멀티모듈을 위한 피드 상세조회 리팩토링
  api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  api/src/main/java/com/programmers/bucketback/domains/feed/application/dto/response/FeedGetServiceResponse.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedReader.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedDetail.java
Labels: refactor, SPRINT5

#114 [OMCT-247] 멀티모듈을 위한 error 패키지 리팩토링
  api/src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  api/src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  api/src/main/java/com/programmers/bucketback/domains/comment/application/CommentValidator.java
  api/src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  api/src/main/java/com/programmers/bucketback/domains/item/application/ItemEnrollValidator.java
  api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewValidator.java
  api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  api/src/main/java/com/programmers/bucketback/global/config/security/SecurityUtils.java
  api/src/main/java/com/programmers/bucketback/global/error/ErrorResponse.java
  api/src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java
  common/build.gradle
  common/src/main/java/com/programmers/bucketback/Hobby.java
  common/src/main/java/com/programmers/bucketback/error/BusinessException.java
  common/src/main/java/com/programmers/bucketback/error/EntityNotFoundException.java
  common/src/main/java/com/programmers/bucketback/error/ErrorCode.java
  domain/src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java
  domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
  domain/src/main/java/com/programmers/bucketback/domains/comment/domain/vo/Content.java
  domain/src/main/java/com/programmers/bucketback/domains/comment/implementation/CommentReader.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/domain/FeedContent.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedAppender.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedReader.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedRemover.java
  domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedSortCondition.java
  domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReader.java
  domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemReader.java
  domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemReader.java
  domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemValidator.java
  domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/Introduction.java
  domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/LoginInfo.java
  domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/Nickname.java
  domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberChecker.java
  domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberReader.java
  domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewReader.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/domain/vo/Content.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteReader.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteSortCondition.java
  domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteStatusCondition.java
  infrastructure/build.gradle
  infrastructure/src/main/java/com/programmers/bucketback/crawling/CoupangCrawler.java
  infrastructure/src/main/java/com/programmers/bucketback/crawling/DanawaCrawler.java
  infrastructure/src/main/java/com/programmers/bucketback/crawling/NaverCrawler.java
  infrastructure/src/main/java/com/programmers/bucketback/crawling/WebSite.java
Labels: refactor, SPRINT5

#119 [NO-JIRA] yml 파일 수정
  .github/workflows/CICD.yml
Labels: refactor, SPRINT5

#120 [OMCT-252] S3 회원 프로필 이미지 수정 기능 구현
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
  bucketback-infrastructure/build.gradle
  bucketback-infrastructure/src/main/java/com/programmers/bucketback/s3/S3Manager.java
  bucketback-infrastructure/src/main/java/com/programmers/bucketback/s3/config/S3Configuration.java
Labels: enhancement, SPRINT5

#122 [NO-JIRA] 커서 조회 시 빈 목록일 경우 예외 발생하는 버그 해결 + CursorUtils 클래스 리팩토링
  bucketback-domain/src/main/java/com/programmers/bucketback/common/cursor/CursorUtils.java
Labels: bug, refactor, SPRINT5

#121 [OMCT-249] JWT 토큰 유효성 체크 API 구현
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberCheckJwtResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberSecurityManager.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/dto/response/MemberCheckJwtServiceResponse.java
Labels: enhancement, SPRINT5

#123 [OMCT-261] enum 리팩토링
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketUpdateRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/dto/request/FeedGetCursorServiceRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/hobby/application/HobbyService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/dto/request/InventoryCreateRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryGetResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/dto/request/ItemEnrollRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemEnrollServiceRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/VoteCreateServiceRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/global/annotation/Enum.java
  bucketback-api/src/main/java/com/programmers/bucketback/global/validator/EnumValidator.java
  bucketback-common/build.gradle
  bucketback-domain/src/main/java/com/programmers/bucketback/common/model/Hobby.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/domain/Bucket.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/model/BucketGetServiceResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/model/BucketProfile.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursorImpl.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedCursorReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/domain/Inventory.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryAppender.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryGetServiceResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryInfoSummary.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryProfile.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepository.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/domain/Item.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemAppender.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteCreateImplRequest.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursorImpl.java
Labels: refactor, SPRINT5

#125 [NO-JIRA] 아이템 검색 목록 조회에 size를 주지 않으면 예외 발생하는 버그 수정
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemCursorReader.java
Labels: bug, SPRINT5

#126 [NO-JIRA] 아이템 등록 기능 버그 수정
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemEnrollService.java
Labels: bug, SPRINT5

#129 [NO-JIRA] 피드 목록 조회 매직 넘버 제거
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedCursorReader.java
Labels: refactor, SPRINT6

#127 [NO-JIRA] 버킷 등록을 위한 버그 수정 및 매직넘버 제거
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
Labels: bug, SPRINT6

#128 [NO-JIRA] Vote 조회 리팩토링
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberRemover.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoterAppender.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteSortCondition.java
Labels: refactor, SPRINT6

#132 [NO-JIRA] 리뷰 리팩토링
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewAppender.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewCursorReader.java
Labels: refactor, SPRINT6

#133 [NO-JIRA] 아이템 URL 길이 설정
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/domain/Item.java
Labels: refactor, SPRINT6

#131 [NO-JIRA] JWT 관련 예외 처리 추가 & Sercurity 관련 예외 처리 변경
  bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/SecurityUtils.java
  bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtAuthenticationFilter.java
  bucketback-api/src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java
  bucketback-common/src/main/java/com/programmers/bucketback/error/ErrorCode.java
Labels: enhancement, SPRINT6

#136 [NO-JIRA] 피드, 아이템 검색, 나의 아이템, 리뷰, 목록조회 totalCount 변수 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/api/response/FeedGetByCursorResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/dto/response/FeedGetByCursorServiceResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetByCursorResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/dto/response/MemberItemGetByCursorResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetByCursorResponse.java
Labels: refactor, SPRINT6

#134 [No-JIRA] cursor 변수명 수정 및 50번 api 커서 Util클래스 적용
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetMemberItemResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/dto/response/CommentGetCursorResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoriesGetResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryGetReviewedItemResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/comment/implementation/CommentReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/comment/repository/CommentSummary.java
Labels: refactor, SPRINT6

#135 [NO-JIRA] list에만 final컨벤션이 붙는 문제 및 FeedContent 디미터 법칙 해결
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/domain/Bucket.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/domain/Inventory.java
Labels: refactor, SPRINT6

#137 [NO-JIRA] 피드 댓글 목록 조회 반환 타입 수정
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/dto/response/CommentGetCursorResponse.java
Labels: bug, SPRINT6

#139 [OMCT-286] 리뷰생성할 때 아이템 아이디를 반환 하도록 기능 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewCreateResponse.java
Labels: enhancement, SPRINT6

#138 [OMCT-284] 리뷰 목록 조회 isReviewed 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetByCursorResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewGetByCursorServiceResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewCursorReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewStatistics.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/model/ReviewCursorSummary.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursorImpl.java
Labels: enhancement, SPRINT6

#142 [NO-JIRA] hobbyValue 적용, profile image,inventoryinfo 주석 해제
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryGetResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryInfoSummary.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberProfile.java
Labels: bug, refactor, SPRINT6

#140 [NO-JIRA] 투표 상세 조회 관련 버그 수정
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VoteGetServiceResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteDetail.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteDetailInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteSummary.java
Labels: bug, SPRINT6

#141 [NO-JIRA] 회원 관련 버그 수정
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberProfile.java
Labels: bug, SPRINT6

#143 [OMCT-289] 나의 아이템 목록 조회에 취미 파라미터 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/common/model/Hobby.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursorImpl.java
Labels: enhancement, SPRINT6

#144 [NO-JIRA] 피드 목록조회, 리뷰 목록조회에 프로필 이미지 반환 추가
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursorImpl.java
Labels: enhancement, SPRINT6

#145 [NO-JIRA] 회원 프로필 이미지 관련 기능 추가 (프로필 이미지 삭제, 피드 목록 조회 시 프로필 이미지 반환)
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberRemover.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java
Labels: enhancement, SPRINT6

#146 [NO-JIRA] 피드 목록 조회에서 대소문자 구분 하지 않고 정렬조건 입력 받을 수 있도록 기능 추가
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedSortCondition.java
Labels: enhancement

#147 [NO-JIRA] 리뷰 수정할 때 아이템 아이디 반환 하도록 기능 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewModifyResponse.java
Labels: enhancement, SPRINT6

#149 [OMCT-294] 리뷰 수정을 위한 리뷰 조회 기능 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewGetServiceResponse.java
Labels: enhancement, SPRINT6

#151 [NO-JIRA] 로그인한 회원 조회 시 탈퇴 회원인지 검증하는 로직 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberSecurityManager.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  bucketback-api/src/main/java/com/programmers/bucketback/global/util/MemberUtils.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberRemover.java
Labels: enhancement, SPRINT6

#150 [NO-JIRA] test-fixture 환경 설정
  bucketback-api/build.gradle
  bucketback-domain/build.gradle
Labels: enhancement, SPRINT6

#152 [OMCT-288] bucket-inventory 생성 및 수정시 조회하는 api 통일
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursorImpl.java
Labels: refactor, SPRINT6

#153 [NO-JIRA] 피드 상세 조회 시 레벨 잘못 나오는 버그 수정 & 아이템 총 가격 응답값 추가
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/domain/FeedItem.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java
Labels: bug, enhancement, SPRINT6

#154 [NO-JIRA] 마이페이지 관련 리팩토링
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryProfile.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberReader.java
Labels: refactor, SPRINT6

#155 [NO-JIRA] 회원 삭제 시 유효하지 않은 이메일로 변경 & 불필요한 로직 제거
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/LoginInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberRemover.java
Labels: refactor, enhancement, SPRINT6

#156 [no-jira] 버킷 - 취미 응답값 한글로 변경
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/model/BucketProfile.java
Labels: refactor, SPRINT6

#157 [OMCT-278] 아이템 추가 기능 테스트 추가
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/item/implementation/ItemAppenderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/builder/domain/ItemBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/builder/model/ItemCrawlerInfoBuilder.java
Labels: test, SPRINT6

#158 [OMCT-259] VoteAppender 단위 테스트 추가
  bucketback-domain/build.gradle
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteCreateImplRequest.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/vote/implementation/VoteAppenderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/vote/domain/VoteBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/vote/model/VoteCreateImplRequestBuilder.java
Labels: test, SPRINT6

#160 [OMCT-320] VoteCounter 단위 테스트 추가
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/vote/implementation/VoteCounterTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/vote/domain/VoteBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/vote/domain/VoterBuilder.java
Labels: test, SPRINT6

#161 [OMCT-322] 피드 목록 조회 옵션 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  bucketback-common/src/main/java/com/programmers/bucketback/error/ErrorCode.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedCursorReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
Labels: enhancement, SPRINT6

#163 [OMCT-327] VoteRemover 단위 테스트 추가
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/vote/implementation/VoteRemoverTest.java
Labels: test, SPRINT6

#159 [OMCT-310] bucket 생성 및 수정 테스트
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/bucket/implementation/BucketAppenderTest.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/bucket/implementation/BucketModifierTest.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/item/implementation/ItemAppenderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/common/model/ItemIdRegistryBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/bucket/domain/BucketBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/domain/ItemBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/model/ItemCrawlerInfoBuilder.java
Labels: test, SPRINT6

#162 [OMCT-324] VoteManager 단위 테스트 추가
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/domain/Voter.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteManager.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoterReader.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/vote/implementation/VoteManagerTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/vote/domain/VoterBuilder.java
Labels: refactor, test, SPRINT6

#164 [OMCT-331] 아이템 아이디 목록을 받아서 삭제할 수 있도록 기능 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemDeleteRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/common/model/ItemRemovalList.java
Labels: enhancement, SPRINT6

#166 [OMCT-332] 아이템 목록 조회 테스트
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/item/implementation/ItemCursorReaderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/common/cursor/CursorPageParametersBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/model/ItemCursorSummaryBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/model/ItemSummaryBuilder.java
Labels: test, SPRINT6

#167 [OMCT-333] 아이템 키워드 검색 기능 추가
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/item/implementation/ItemFinderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/domain/ItemBuilder.java
Labels: test, SPRINT6

#171 [No-jira] 버킷 조회(상세,목록)시 아이템의 총 금액 필드 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/model/BucketGetServiceResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/model/BucketSummary.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursorImpl.java
Labels: bug, SPRINT6

#169 [OMCT-335] 나의 아이템 추가 테스트
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/item/implementation/ItemCursorReaderTest.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/item/implementation/MemberItemAppenderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/common/cursor/CursorPageParametersBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/domain/ItemBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/model/ItemCrawlerInfoBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/model/ItemCursorSummaryBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/model/ItemSummaryBuilder.java
Labels: test, SPRINT6

#170 [OMCT-336] 나의 아이템 조회 테스트
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/item/implementation/MemberItemReaderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/common/cursor/CursorPageParametersBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/model/MemberItemSummaryBuilder.java
Labels: test, SPRINT6

#173 [OMCT-344] 리뷰 목록 조회 테스트
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/review/implementation/ReviewCursorReaderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/common/cursor/CursorPageParametersBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/review/ReviewCursorSummaryBuilder.java
Labels: test, SPRINT6

#180 [OMCT-367] 피드 상세 조회 시 취미 영어로 반환되는 버그 수정
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedInfo.java
Labels: bug, SPRINT7

#176 [OMCT-346] CommentModifier 단위 테스트 추가
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/comment/implementation/CommentModifierTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/comment/domain/CommentBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/feed/FeedBuilder.java
Labels: test, SPRINT6

#177 [OMCT-349] CommentAppender 단위 테스트 추가
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/comment/implementation/CommentAppender.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/comment/implementation/CommentAppenderTest.java
Labels: test, SPRINT6

#172 [Omct 311] BucketReader Test
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepository.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/bucket/implementation/BucketModifierTest.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/bucket/implementation/BucketReaderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/bucket/domain/BucketBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/bucket/model/BucketMemberItemSummaryBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/bucket/model/BucketSummaryBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/domain/ItemBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/item/domain/MemberItemBuilder.java
Labels: test, SPRINT6

#184 [NO-JIRA] 피드 목록 조회 limit 버그 수정
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
Labels: bug, SPRINT7

#186 [NO-JIRA] 탈퇴한 회원 닉네임 삭제
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/Nickname.java
Labels: bug, SPRINT7

#182 [NO-JIRA] 레디스 설정 추가
  bucketback-infrastructure/build.gradle
  bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/config/RedisConfig.java
Labels: enhancement, SPRINT7

#189 [OMCT-378] 로그를 클라우드 워치에 저장할 수 있도록 기능 추가
  bucketback-infrastructure/build.gradle
  bucketback-infrastructure/src/main/resources/logback-spring.xml
Labels: enhancement, SPRINT7

#188 [NO-JIRA] 아이템 목록 조회 좋아요 누른 피드 보기 버그 수정
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedCursorReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
Labels: bug, SPRINT7

#191 [NO-JIRA] 최신순으로 정렬 해서 피드를 가져올 때 최신으로 반환이 안되는 버그 수정
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
Labels: bug, SPRINT7

#190 [NO-JIRA] 회원 프로필 이미지 주소 대신 이미지 이름으로 저장하도록 변경
  bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberProfile.java
Labels: refactor, SPRINT7

#192 [NO-JIRA] 내가 좋아요 누른 피드 않보이는 버그 수정
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
Labels: bug, SPRINT7

#196 [OMCT-274] 아이템 랭킹 수정
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemEnrollService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/implement/ItemRanking.java
Labels: refactor, SPRINT7

#197 [NO-JIRA] 좋아요 눌렀을 때 좋아요 누른 사람의 정보가 feed 작성자 처럼 반환 되는 버그 수정
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
Labels: bug, SPRINT7

#194 [OMCT-369] 피드 목록 조회 테스트 추가
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/feed/implementation/FeedCursorReaderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/feed/model/FeedCursorSummaryBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/feed/model/FeedCursorSummaryLikeBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/member/domain/MemberBuilder.java
Labels: test, SPRINT7

#195 [OMCT-379] FeedAppender 구현 클래스 테스트 추가
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedAppender.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/feed/implementation/FeedAppenderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/feed/model/FeedCreateServiceRequestBuilder.java
Labels: test, SPRINT7

#199 [NO-JIRA] 커서 목록조회 : 총 개수를 read 해오는 반환값 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetByCursorResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetMemberItemResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/dto/response/BucketGetCursorServiceResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/dto/response/BucketGetMemberItemServiceResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/dto/response/CommentGetCursorResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/dto/response/CommentGetCursorServiceResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/dto/response/MemberItemGetByCursorResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/dto/MemberItemGetServiceResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepository.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/comment/implementation/CommentReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepository.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
Labels: refactor, SPRINT7

#200 [NO-JIRA] 피드 아이템에서 아이템 아이디가 아니라 피드 아이템이 반환 되는 버그 수정
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedItemInfo.java
Labels: bug, SPRINT7

#201 [NO-JIRA] validation과 global handler exception 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentModifyRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java
  bucketback-common/src/main/java/com/programmers/bucketback/error/ErrorCode.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/domain/Review.java
Labels: enhancement, SPRINT7
