Repository bucket-back/bucket-back-backend, pull requests merged in 2023-12, with the labels that each got.

#207 [NO-JIRA] 인벤토리 limit쿼리 버그 해결
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java
Labels: bug, SPRINT7

#208 [NO-JIRA] 투표 키워드 검색해서 나온 전체 결과수 반환값 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByKeywordResponse.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VoteGetByKeywordServiceResponse.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteReader.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursor.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursorImpl.java
Labels: enhancement, SPRINT7

#210 [NO-JIRA] 잘못된 네이밍 수정
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByKeywordResponse.java
Labels: bug, SPRINT7

#212 [OMCT-352] inventoryReader 테스트 기능 구현
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/inventory/implementation/InventoryAppenderTest.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/inventory/implementation/InventoryModifierTest.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReaderTest.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/inventory/domain/InventoryBuilder.java
  bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/review/ReviewBuilder.java
Labels: test

#202 [OMCT-380] 피드 수정 테스트 기능 추가
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/feed/implementation/FeedModifierTest.java
Labels: test, SPRINT7

#213 [OMCT-410] domain validation test 및 refactoring
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/bucket/domain/BucketInfoTest.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/feed/domain/FeedContentTest.java
Labels: refactor, test

#215 [OMCT-408] 댓글 생성에 대한 알림 기능 구현
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/event/CommentCreateEvent.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/event/CommentEventType.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/sse/PayLoadProvider.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/sse/SseController.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/sse/SseEmitters.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/sse/SseEventListener.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/sse/SsePayload.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/sse/SseService.java
  bucketback-api/src/test/java/com/programmers/bucketback/domains/sse/SseEmittersTest.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/comment/domain/Comment.java
  bucketback-domain/src/test/java/com/programmers/bucketback/domains/comment/implementation/CommentModifierTest.java
Labels: enhancement

#214 [OMCT-409] 최대 투표자 수를 제한하는 요구사항 추가
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/VoteCreateServiceRequest.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteAppender.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteManager.java
  bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteCreateImplRequest.java
Labels: enhancement
