Repository bucket-back/bucket-back-backend, pull requests merged in 2023-10, with the labels that each got.

#1 [OMCT-38] Member 회원가입 기능 구현
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/application/dto/request/SignupMemberServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
Labels: SPRINT2

#2 [OMCT-48] : Item 크롤링 기능 구현
  build.gradle
  src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/CoupangCrawler.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/DanawaCrawler.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/ItemInfo.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/NaverCrawler.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/WebCrawler.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/WebSite.java
  src/main/java/com/programmers/bucketback/domains/item/domain/Item.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: SPRINT2

#4 [OMCT-52] Swagger 버전 업데이트
  build.gradle
  src/main/java/com/programmers/bucketback/global/config/SwaggerConfiguration.java
Labels: SPRINT2

#5 [NO-JIRA] 입력받은 데이터 검증하는 enum annotation 추가
  src/main/java/com/programmers/bucketback/domains/common/Hobby.java
  src/main/java/com/programmers/bucketback/global/annotation/Enum.java
  src/main/java/com/programmers/bucketback/global/validator/EnumValidator.java
Labels: enhancement, SPRINT2

#8 [OMCT-51] 회원 삭제 기능 구현
  src/main/java/com/programmers/bucketback/domains/common/BaseEntity.java
  src/main/java/com/programmers/bucketback/domains/common/MemberUtils.java
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  src/main/java/com/programmers/bucketback/domains/member/domain/MemberSecurity.java
  src/main/java/com/programmers/bucketback/domains/member/domain/MemberStatus.java
  src/main/java/com/programmers/bucketback/global/config/security/ApplicationConfiguration.java
  src/main/java/com/programmers/bucketback/global/config/security/SecurityConfiguration.java
  src/main/java/com/programmers/bucketback/global/config/security/SecurityUtils.java
  src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtService.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: SPRINT2

#9 [OMCT - 39] Item 등록 구현
  src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/request/ItemEnrollRequest.java
  src/main/java/com/programmers/bucketback/domains/item/application/CreateItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/EnrollItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/CoupangCrawler.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/DanawaCrawler.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/ItemInfo.java
  src/main/java/com/programmers/bucketback/domains/item/application/crawling/NaverCrawler.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/CreateItemServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/EnrollItemServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/item/domain/Item.java
Labels: enhancement, SPRINT2

#11 [NO-ZIRA] 로그인 시 memberId 반환
  src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberLoginResponse.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/application/dto/response/LoginMemberServiceResponse.java
Labels: SPRINT2

#13 [OMCT-66] Member 삭제 기능 구현
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/domain/LoginInfo.java
  src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
Labels: enhancement, SPRINT2

#12 [OMCT-65] Member 프로필 수정 기능 구현
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/application/dto/request/UpdateProfileMemberServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/member/domain/LoginInfo.java
  src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
Labels: enhancement, SPRINT2

#10 [NO-JIRA] 서비스 구현과 비지니스 코드 분리 & 로그인 정보 개념 객체로 추출
  src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java
  src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberLoginResponse.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberAppender.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java
  src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
  src/main/java/com/programmers/bucketback/domains/member/application/SecurityManager.java
  src/main/java/com/programmers/bucketback/domains/member/application/dto/request/SignupMemberServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/member/application/dto/request/UpdateProfileMemberServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/member/application/dto/response/LoginMemberServiceResponse.java
  src/main/java/com/programmers/bucketback/domains/member/domain/LoginInfo.java
  src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
  src/main/java/com/programmers/bucketback/domains/member/repository/MemberRepository.java
Labels: refactor, SPRINT2

#6 [OMCT - 53 ] Bucket 생성 구현
  src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketUpdateRequest.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketContent.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketModifier.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketRemover.java
  src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
  src/main/java/com/programmers/bucketback/domains/bucket/domain/Bucket.java
  src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java
  src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketItem.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: SPRINT2

#14 [OMCT - 40] Item 담기 기능 구현
  src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
  src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemAddRequest.java
  src/main/java/com/programmers/bucketback/domains/item/application/AddMemberItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemReader.java
  src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/AddMemberItemServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/CreateItemServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/item/application/dto/EnrollItemServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/item/domain/MemberItem.java
  src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT2

#20 [OMCT-71] Vote 생성 기능 구현
  src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteCreateResponse.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteAppender.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/CreateVoteServiceRequest.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Voter.java
Labels: enhancement, SPRINT3

#21 build: query dsl 설정파일 추가
  build.gradle
  src/main/java/com/programmers/bucketback/global/config/QuerydslConfig.java
Labels: SPRINT3

#23 [NO-JIRA] Item과 Vote 연관관계 제거
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteAppender.java
  src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
  src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
Labels: SPRINT3

#22 [OMCT-43] 리뷰 등록 기능 추가
  src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
  src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewAppender.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewReader.java
  src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
  src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewContent.java
  src/main/java/com/programmers/bucketback/domains/review/domain/Review.java
  src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepository.java
  src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
Labels: enhancement, SPRINT3
